### ISSUE TITLE
Make Install fails for Vim 7.4.1525

### ISSUE THREAD

**Issue by barberousse** [Homebrew/legacy-homebrew#50197]
[gist-log](https://gist.github.com/anonymous/e937c807f08e09a987b3) Not too familiar with make and what looks like an issue doing something with language files, but its stopping me from completing a full install.

**Comment by dunn** [comment]
Looks like the error is higher up: https://gist.github.com/anonymous/e937c807f08e09a987b3#file-03-make-L160-L165

Not sure, but try `HOMEBREW_MAKE_JOBS=1 brew install ...`

**Comment by barberousse** [comment]
Comes back as
```
~/Source/authoring-tool λ HOMEBREW_MAKE_JOBS=1 brew install vim
==> Downloading https://github.com/vim/vim/archive/v7.4.1525.tar.gz
Already downloaded: /Library/Caches/Homebrew/vim-7.4.1525.tar.gz
==> ./configure --prefix=/usr/local --mandir=/usr/local/Cellar/vim/7.4.1525/share/man --enable-multibyte --with-tlib=ncurses --enable-cscope --with-compiledby=Homebrew --enable-perlinterp --enable-pythoninterp --enable-rubyinterp --enable
==> make
==> make install prefix=/usr/local/Cellar/vim/7.4.1525 STRIP=true
Last 15 lines from /Users/bbarberousse/Library/Logs/Homebrew/vim/03.make:
link.sh: If this fails too, try creating an empty auto/link.sed file.
link.sh: Using auto/link.sed file to omit a few libraries
 env LD_RUN_PATH=/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE /usr/bin/clang   -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib -L/usr/local/lib -Wl,-headerpad_max_install_names 	-o vim objects/buffer.o objects/blowfish.o objects/charset.o objects/crypt.o objects/crypt_zip.o objects/diff.o objects/digraph.o objects/edit.o objects/eval.o objects/ex_cmds.o objects/ex_cmds2.o objects/ex_docmd.o objects/ex_eval.o objects/ex_getln.o objects/fileio.o objects/fold.o objects/getchar.o objects/hardcopy.o objects/hashtab.o  objects/if_cscope.o objects/if_xcmdsrv.o objects/mark.o objects/memline.o objects/menu.o objects/message.o objects/misc1.o objects/misc2.o objects/move.o objects/mbyte.o objects/normal.o objects/ops.o objects/option.o objects/os_unix.o objects/pathdef.o objects/popupmnu.o objects/quickfix.o objects/regexp.o objects/screen.o objects/search.o objects/sha256.o objects/spell.o objects/syntax.o objects/tag.o objects/term.o objects/ui.o objects/undo.o objects/version.o objects/window.o    objects/if_perl.o objects/if_perlsfio.o objects/if_python.o   objects/if_ruby.o objects/os_macosx.o objects/os_mac_conv.o  objects/netbeans.o objects/channel.o  objects/json.o objects/main.o objects/memfile.o        -lm  -lncurses -framework Cocoa   -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -framework Python   -lruby.2.3.0 -lobjc -L/usr/local/Cellar/ruby/2.3.0/lib    
link.sh: Linked fine with a few libraries omitted
/bin/sh ./mkinstalldirs /usr/local/Cellar/vim/7.4.1525/bin
mkdir /usr/local/Cellar/vim/7.4.1525/bin
chmod 755 /usr/local/Cellar/vim/7.4.1525/bin
if test -f /usr/local/Cellar/vim/7.4.1525/bin/vim; then \
	  mv -f /usr/local/Cellar/vim/7.4.1525/bin/vim /usr/local/Cellar/vim/7.4.1525/bin/vim.rm; \
	  rm -f /usr/local/Cellar/vim/7.4.1525/bin/vim.rm; \
	fi
cp vim /usr/local/Cellar/vim/7.4.1525/bin
cp: vim: No such file or directory
make[1]: *** [installvimbin] Error 1
make: *** [install] Error 2

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
Make Install fails for Vim 7.4.488 https://github.com/Homebrew/homebrew/issues/50197
vim  7.4.488 build fails if Homebrew ruby is installed but /usr/bin/ruby comes first in PATH https://github.com/Homebrew/homebrew/issues/33705
```

**Comment by chdiza** [comment]
That's an out of date Vim formula.  The current version is 7.4.1589, but you're trying to build 7.4.1401, and your HB installation is three weeks old.  Vim development has been proceeding rapidly lately (including makefile changes), and some of the pointreleases are broken. I would try to build Vim from HEAD, and outside of HB, to see what happens.

**Comment by dunn** [comment]
Oh yeah, missed that.  First `brew update` then try installing again.

**Comment by chdiza** [comment]
Also, the title of this issue is misleading, since at no point was a Vim 7.4.488 build attempted.  "7.4.488" only comes from the "maybe these OTHER issues will help" part of the failure message.

**Comment by apjanke** [comment]
Edited title for clarity.

I just merged the formula update for `vim` 7.4.1589 (#50245), so if you do a `brew update` now you'll get that one.

**Comment by zopyx** [comment]
The installation/update of vim is still broken even with /usr/local/bin/ruby


/if_xcmdsrv.o objects/mark.o objects/memline.o objects/menu.o objects/message.o objects/misc1.o objects/misc2.o objects/move.o objects/mbyte.o objects/normal.o objects/ops.o objects/option.o objects/os_unix.o objects/pathdef.o objects/popupmnu.o objects/quickfix.o objects/regexp.o objects/screen.o objects/search.o objects/sha256.o objects/spell.o objects/syntax.o objects/tag.o objects/term.o objects/ui.o objects/undo.o objects/version.o objects/window.o    objects/if_perl.o objects/if_perlsfio.o objects/if_python.o   objects/if_ruby.o objects/os_macosx.o objects/os_mac_conv.o  objects/netbeans.o objects/channel.o  objects/json.o objects/main.o objects/memfile.o        -lm  -lncurses -liconv -framework Cocoa   -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -lperl -framework Python   -lruby.2.3.0 -lpthread -ldl -lobjc -L/usr/local/Cellar/ruby/2.3.0/lib
Undefined symbols for architecture x86_64:
  "_PyUnicodeUCS4_AsEncodedString", referenced from:
      _StringToLine in if_python.o
      _StringToChars in if_python.o
      __ConvertFromPyObject in if_python.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [vim] Error 1
make: *** [first] Error 2

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
Make Install fails for Vim 7.4.1525 https://github.com/Homebrew/homebrew/issues/50197
vim  7.4.488 build fails if Homebrew ruby is installed but /usr/bin/ruby comes first in PATH https://github.com/Homebrew/homebrew/issues/33705

Suxmac:~ ajung$ which ruby
/usr/local/bin/ruby


Suxmac:~ ajung$ echo $PATH
/opt/local/bin:/opt/local/sbin:/opt/local/bin:/opt/local/sbin:/Users/ajung/.nix-profile/bin:/Users/ajung/.nix-profile/sbin:/opt/local/bin:/opt/local/sbin:/opt/local/bin:/opt/local/sbin:/opt/local/bin:/opt/local/sbin:/opt/local/bin:/opt/local/sbin:/usr/local/heroku/bin:/usr/local/bin:/Applications/MuseScore2.app/Contents/MacOS:#/opt/local/bin:/opt/weasyprint/bin:/opt/buildout.python/bin:/opt/dita-ot-2.2.1/bin:/usr/local/AHFormatterV63:/opt/prince-10/bin/:/opt/vivliostyle/vivliostyle/:/opt/ditac-2_5_6/bin:/opt/sphinx/bin:/opt/PDFreactor/bin/:/opt/speedata-publisher/bin:/Applications/calibre.app/Contents/MacOS:/Users/ajung/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/MacGPG2/bin:/Users/ajung/bin/FDK/Tools/osx

**Comment by ilovezfs** [comment]
@zopyx It's probably your python, which I'm guessing isn't the bottled brew python. You need to follow https://git.io/brew-troubleshooting

**Comment by decimalbell** [comment]
Make Install fails for Vim 7.4.1525
https://gist.github.com/anonymous/bfb2aea5a0566780c600

**Comment by dunn** [comment]
@decimalbell try upgrading Xcode first:
```
Warning: Your Xcode (6.3.2) is outdated
Please update to Xcode 7.2.1.
Xcode can be updated from the App Store.

**Comment by UniqMartin** [comment]
Vim is at 7.4.1795 by now. Closing as I suspect this is likely no longer a problem. I'm happy to reopen, should I be mistaken.
